### ISSUE TITLE
Revise README.MD so that the rendering error is made clear as a github issue and not an oversight.

### ISSUE THREAD

**Issue by NoelJB** [SunStarSys/cms#3]
README.MD is rendered with this passage;

`Unable to render rich display

Parse error on line 1:
mindmap root((mind
^
Expecting 'open_directive', 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'

For more information, see https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectivness<br/>and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid`
      
Apparently, that exists to highlight a deficiency in github that works properly in Orion, but nothing in the context would make that clear to an observer.

**Comment by joesuf4** [comment]
Updated document to highlight the fact that these diagrams are mermaid.js rendering tests that Orion supports.  GitHub does not currently support mindmap graphs.  See https://sunstarsys.com/orion/features for the live rendering.
